CREATE TABLE "WL_TC_TOWNS"

(

"TOWN_ID" INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
"COUNTY_ID" INT,
"TOWN" VARCHAR(255),
"BS" VARCHAR(255)
);

CREATE TABLE "WL_TC_COUNTIES"

(

"COUNTIES_ID" INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
"COUNTRY_ID" INT,
"REGION" INT,
"COUNTY" VARCHAR(255)

);

CREATE TABLE "WL_TC_COUNTRIES"

(

"COUNTRY_ID" INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
"COUNTRY" VARCHAR(255)

);

CREATE TABLE "WL_TC_REGIONS"

(

"REGION_ID" INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1), 
"COUNTRY_ID" INT,
"REGION" VARCHAR(255),
"RANK" INT

);